

class Constants(object):
    WELD = False
    CTRE_MAX_VELOCITY = 25000

    if WELD:
        LEFT_DISTANCE_F = 0.1
        LEFT_DISTANCE_P = 0.1
        LEFT_DISTANCE_I = 0
        LEFT_DISTANCE_D = 0

        LEFT_VELOCITY_F = 1023 / CTRE_MAX_VELOCITY
        LEFT_VELOCITY_P = 102.3/3000
        LEFT_VELOCITY_I = 0
        LEFT_VELOCITY_D = 0
        
        RIGHT_DISTANCE_F = 0.1
        RIGHT_DISTANCE_P = 0.07
        RIGHT_DISTANCE_I = 0.001
        RIGHT_DISTANCE_D = 0

        RIGHT_VELOCITY_F = 1023 / CTRE_MAX_VELOCITY
        RIGHT_VELOCITY_P = 102.3/3000
        RIGHT_VELOCITY_I = 0
        RIGHT_VELOCITY_D = 0

    else:  # RIVET
        LEFT_DISTANCE_F = 0
        LEFT_DISTANCE_P = 0.1
        LEFT_DISTANCE_I = 0
        LEFT_DISTANCE_D = 0

        LEFT_VELOCITY_F = 1023 / CTRE_MAX_VELOCITY
        LEFT_VELOCITY_P = 1.75 * 102.3 / 1600
        LEFT_VELOCITY_I = 0
        LEFT_VELOCITY_D = 0
        
        RIGHT_DISTANCE_F = 0
        RIGHT_DISTANCE_P = 0.1
        RIGHT_DISTANCE_I = 0
        RIGHT_DISTANCE_D = 0

        RIGHT_VELOCITY_F = 1023 / CTRE_MAX_VELOCITY
        RIGHT_VELOCITY_P = 1.75 * 102.3 / 1600
        RIGHT_VELOCITY_I = 0
        RIGHT_VELOCITY_D = 0

    ENCODER_TICKS_TO_AXLE_REVS = 4096
    NEO_MAX_VELOCITY = 5600
    TIMEOUT_MS = 20
    LOWEST_ENABLED_ELEVATOR_POS = 1

    # Elevator Constants
    LIFT_ELEVATOR_FF = 0.00015
    LIFT_ELEVATOR_P = 5e-5
    LIFT_ELEVATOR_I = 1e-6
    LIFT_ELEVATOR_D = 0

    LIFT_MAX_VELOCITY = 3000 / 2
    LIFT_MAX_ACCEL = 3000 / 2

    ELEVATOR_MAX_VELOCITY = 4800
    ELEVATOR_MAX_ACCEL = 4800
